language: node_js
sudo: false
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
  - /^greenkeeper/.*$/
env:
  - TEST_SUITE=test
  - TEST_SUITE=test:integration
services:
  - redis-server
script: npm run $TEST_SUITE
addons:
  sauce_connect: true
