language: node_js
sudo: false
dist: trusty
install:
  - npm i
  - npm i cypress
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
  - TEST_SUITE=lint
  - TEST_SUITE=test
  - TEST_SUITE=test:cy
services:
  - redis-server
script: npm run $TEST_SUITE
addons:
  sauce_connect: true
