language: node_js
sudo: false
dist: trusty
cache:
  bundler: true
  directories:
  - node_modules
branches:
  only:
  - master
env:
- TEST_SUITE=test
- TEST_SUITE=test:integration
before_install:
  - if [ "${TEST_SUITE}" != "test:integration" ]; then unset SAUCE_USERNAME && unset SAUCE_ACCESS_KEY; fi
script: npm run $TEST_SUITE
addons:
  sauce_connect: true
